# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-31 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.TipoProducto'),
        ),
    ]
