# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-31 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=255)),
                ('rut', models.TextField(max_length=255)),
                ('correo', models.TextField(max_length=255)),
                ('direccion', models.TextField(max_length=255)),
            ],
        ),
    ]
